// ===== VIENTRE LIBRE · RESET 21 — 21-Day Program Data =====
// Source: OFFER-LOCK-FINAL-v1.0.md — DO NOT MODIFY content without re-lock

export interface DayData {
  title: string;
  subtitle: string;
  module: number;
  moduleName: string;
  videoDuration: string;
  phase: "desinflama" | "reprograma" | "mapea";
  action: string;
  actionNote?: string;
  reflection: string;
  downloads: string[];
}

export const PHASES = {
  desinflama: { label: "Fase 1 — Desinflama Rápido", color: "#E07856", days: "Días 1–7" },
  reprograma: { label: "Fase 2 — Reprograma", color: "#7B68AE", days: "Días 8–14" },
  mapea: { label: "Fase 3 — Reintroduce y Mapea", color: "#5C6F47", days: "Días 15–21" },
};

export const MODULES = [
  { num: 1, title: "La Paradoja Tiene Nombre", duration: "15:20" },
  { num: 2, title: "El Desinflama Rápido", duration: "18:05" },
  { num: 3, title: "El Reset Hormonal", duration: "17:40" },
  { num: 4, title: "El Mapa es Tuyo", duration: "16:10" },
];

export const programData: Record<number, DayData> = {
  1: {
    title: "La Paradoja Tiene Nombre",
    subtitle: "Entiende exactamente por qué tu cuerpo cambió y por qué los alimentos sanos se volvieron tus villanos.",
    module: 1,
    moduleName: "La Paradoja Tiene Nombre",
    videoDuration: "15:20",
    phase: "desinflama",
    action: "Hoy no cambias nada de lo que comes. Solo registra en el Tracker cómo te sientes exactamente a las 4:00 PM — nivel de hinchazón del 1 al 10, ropa que llevas, qué comiste en las últimas 4 horas.",
    actionNote: "Esta es tu línea de base. Guárdala — la necesitarás el Día 21.",
    reflection: "¿Qué sentiste cuando descubriste que los alimentos que creías que eran tus aliados podrían ser tus villanos?",
    downloads: ["Tu Informe Personal de la Paradoja", "El Tracker Ciclo-Intestinal"],
  },
  2: {
    title: "Conoce a Tus 5 Villanos",
    subtitle: "Brócoli, garbanzos, cebolla/ajo, avena, kale — el mecanismo exacto por el que te inflaman y su sustituto inmediato.",
    module: 2,
    moduleName: "El Desinflama Rápido",
    videoDuration: "18:05",
    phase: "desinflama",
    action: "Lee los 5 Expedientes de los Villanos completos. Marca en el Tracker cuáles consumes con más frecuencia. Esos son TUS villanos prioritarios.",
    reflection: "¿Cuál de los 5 Villanos te sorprende más? ¿Cuál es el más difícil de imaginar sin él en tu dieta?",
    downloads: ["Los 5 Expedientes de los Villanos", "El Conversor Anti-Villanos"],
  },
  3: {
    title: "El Orden Glucémico — Fibra Primero",
    subtitle: "Un cambio de orden que puede reducir tu pico de glucosa hasta un 73%. Sin eliminar nada. Solo reordenar.",
    module: 2,
    moduleName: "El Desinflama Rápido",
    videoDuration: "18:05",
    phase: "desinflama",
    action: "En todas tus comidas de hoy aplica el orden biológico correcto: (1) verduras/fibra → (2) proteína → (3) carbohidratos. Sin excepciones.",
    actionNote: "Si el plato ya viene mezclado, empieza comiendo la parte más verde o proteica primero.",
    reflection: "¿Notaste diferencia en la energía o en la hinchazón a las 3-4 horas de comer?",
    downloads: ["Las 21 Combinaciones Base"],
  },
  4: {
    title: "El Retiro Estratégico Comienza",
    subtitle: "No es una dieta de eliminación para siempre. Es un retiro de 14 días para que tu intestino pueda resetear.",
    module: 2,
    moduleName: "El Desinflama Rápido",
    videoDuration: "18:05",
    phase: "desinflama",
    action: "Retira temporalmente los Villanos identificados como TUS prioritarios. Sustitúyelos con las alternativas del Conversor. Anota en el Tracker qué retiraste y a qué hora.",
    actionNote: "El objetivo NO es comer \"perfecto\". Es darle a tu intestino 14 días sin los detonadores principales para que la inflamación base baje.",
    reflection: "¿Qué emoción sientes al retirar temporalmente un alimento que creías saludable?",
    downloads: ["El Conversor Anti-Villanos"],
  },
  5: {
    title: "Primera Señal Visible",
    subtitle: "Si aplicaste los Días 3-4 correctamente, hoy deberías notar la primera diferencia tangible.",
    module: 2,
    moduleName: "El Desinflama Rápido",
    videoDuration: "18:05",
    phase: "desinflama",
    action: "Mide tu circunferencia abdominal a las 8 AM y a las 8 PM. Anota la diferencia. Compara tu nivel de hinchazón a las 4 PM con el registro del Día 1.",
    reflection: "¿Hay diferencia entre cómo te sientes hoy y el Día 1? Pequeña o grande — anota exactamente qué cambió.",
    downloads: ["El Tracker Ciclo-Intestinal"],
  },
  6: {
    title: "Los Ingredientes Disfrazados",
    subtitle: "Los 22 ingredientes con FODMAP ocultos que se esconden en productos etiquetados como 'saludables'.",
    module: 2,
    moduleName: "El Desinflama Rápido",
    videoDuration: "18:05",
    phase: "desinflama",
    action: "Abre tu despensa y frigorífico. Lee las etiquetas de 3-5 productos que compras habitualmente. Busca: inulina, FOS (fructooligosacáridos), sorbitol, concentrado de manzana, achicoria.",
    actionNote: "Guarda el Índice en el móvil — ábrelo la próxima vez que estés en el supermercado.",
    reflection: "¿Encontraste algún ingrediente oculto en algo que no esperabas? ¿En qué producto?",
    downloads: ["Índice de Etiquetas Anti-Villanos"],
  },
  7: {
    title: "Cierre de Fase 1 — Tu Primera Observación",
    subtitle: "Una semana. Tu intestino empezó a bajar la guardia. Hoy documenta el primer patrón visible.",
    module: 2,
    moduleName: "El Desinflama Rápido",
    videoDuration: "18:05",
    phase: "desinflama",
    action: "Completa la Sección 1 del Mapa Personal de la Paradoja. Documenta: ¿a qué hora del día sientes menos hinchazón? ¿Qué alimento del Conversor funcionó mejor?",
    actionNote: "Mañana empieza la Fase 2. El reset glucémico ya está funcionando — ahora sincronizamos con tus hormonas.",
    reflection: "¿En qué momento de los 7 días notaste la diferencia más clara? ¿Cuál fue la sorpresa más grande?",
    downloads: ["El Mapa Personal de la Paradoja"],
  },
  8: {
    title: "Tu Ciclo y Tu Intestino — La Conexión",
    subtitle: "La conexión que nadie te explicó: tus hormonas controlan directamente la velocidad de tu digestión.",
    module: 3,
    moduleName: "El Reset Hormonal",
    videoDuration: "17:40",
    phase: "reprograma",
    action: "Identifica en qué fase de tu ciclo estás hoy: folicular (días 1-14 post-menstruación), ovulación (día 12-16), lútea (días 15-28), menstrual. Anótalo en el Tracker.",
    actionNote: "Si tienes ciclo irregular o estás en perimenopausia, trabaja por síntomas: hinchazón tipo-menstrual, tipo-mitad-de-ciclo, etc.",
    reflection: "¿Hay algún patrón recurrente que ahora conectes con una fase específica de tu ciclo?",
    downloads: ["El Tracker Ciclo-Intestinal"],
  },
  9: {
    title: "Fase Folicular — Tu Ventana de Mayor Tolerancia",
    subtitle: "En la fase folicular tu tolerancia digestiva es máxima. Es el momento para reintroducir con cautela.",
    module: 3,
    moduleName: "El Reset Hormonal",
    videoDuration: "17:40",
    phase: "reprograma",
    action: "Si estás en fase folicular: puedes probar reintroducir UN villano en cantidad pequeña (solo uno, solo hoy). Registra la respuesta en las próximas 6 horas.",
    actionNote: "Si no estás en fase folicular, sigue con las 21 Combinaciones Base de hoy y registra tu fase actual.",
    reflection: "¿Sientes que tienes más energía o mejor digestión en ciertas semanas del mes que en otras?",
    downloads: ["Las 21 Combinaciones Base"],
  },
  10: {
    title: "El Descanso Nocturno del Intestino",
    subtitle: "Dar al intestino 12 horas de ayuno nocturno activa la limpieza del complejo migratorio motor — el mecanismo de autolimpieza que el SIBO interrumpe.",
    module: 3,
    moduleName: "El Reset Hormonal",
    videoDuration: "17:40",
    phase: "reprograma",
    action: "Esta semana establece una ventana de alimentación de 12 horas: si desayunas a las 8h, cena antes de las 20h. Sin picar después de cenar.",
    actionNote: "No es ayuno intermitente agresivo. Es simplemente respetar el ritmo circadiano de tu digestión.",
    reflection: "¿Cómo amaneces cuando las últimas 12 horas antes de despertar no comiste nada?",
    downloads: [],
  },
  11: {
    title: "El Hack de Glucosa más Sencillo del Protocolo",
    subtitle: "Una cucharadita de vinagre de manzana antes de tu comida principal puede reducir el pico glucémico hasta un 30%.",
    module: 3,
    moduleName: "El Reset Hormonal",
    videoDuration: "17:40",
    phase: "reprograma",
    action: "15 minutos antes de tu comida más grande del día: 1 cucharadita de vinagre de manzana en un vaso de agua. Observa la hinchazón post-comida.",
    actionNote: "Si tienes acidez o gastritis, omite este paso y consúltalo con tu médico.",
    reflection: "¿Notaste menos somnolencia o hinchazón después de la comida donde usaste el vinagre?",
    downloads: [],
  },
  12: {
    title: "Cortisol Nocturno — Por qué Cenar Tarde Te Inflama",
    subtitle: "El cortisol tiene un pico nocturno que se dispara con carbohidratos simples después de las 20h. Esto inflama y retiene agua durante toda la noche.",
    module: 3,
    moduleName: "El Reset Hormonal",
    videoDuration: "17:40",
    phase: "reprograma",
    action: "Cena antes de las 20h esta semana. Si no puedes, aplica la regla de 'proteína + verdura' en cenas tardías — sin cereales ni frutas dulces después de las 20h.",
    reflection: "¿Notas diferencia en cómo amanece tu vientre cuando cenas más temprano o más ligero?",
    downloads: [],
  },
  13: {
    title: "Reconstruyendo Tu Microbiota",
    subtitle: "El orden correcto: resetear antes de repoblar. Muchos probióticos genéricos fallan porque intentan repoblar un intestino que aún no se ha limpiado.",
    module: 3,
    moduleName: "El Reset Hormonal",
    videoDuration: "17:40",
    phase: "reprograma",
    action: "Introduce un alimento fermentado de bajo FODMAP: kéfir de agua, kimchi sin ajo en cantidad pequeña, o miso diluido. Una porción pequeña, con una comida.",
    actionNote: "Si notas gas o malestar con el fermentado, reduce la cantidad o espera a la Fase 3 para introducirlos.",
    reflection: "¿Notaste algún cambio en la digestión con el fermentado — positivo o negativo?",
    downloads: [],
  },
  14: {
    title: "Mitad de Camino — El Cuerpo que Empieza a Ser Tuyo",
    subtitle: "14 días de protocolo. Hoy es el día de documentar, no de hacer más. El reset ya está trabajando.",
    module: 3,
    moduleName: "El Reset Hormonal",
    videoDuration: "17:40",
    phase: "reprograma",
    action: "Completa la Sección 2 del Mapa Personal. Documenta: ¿qué cambió? ¿Qué aún no cambió? ¿Qué sorpresa positiva tuviste?",
    actionNote: "Mañana empieza la Fase 3: la más importante. Vas a saber exactamente qué es TUYO y qué no.",
    reflection: "¿Qué es lo que más ha cambiado desde el Día 1 hasta hoy — en tu cuerpo o en tu relación con la comida?",
    downloads: ["El Mapa Personal de la Paradoja"],
  },
  15: {
    title: "El Protocolo de Reintroducción",
    subtitle: "Cómo testear sistemáticamente cada alimento para saber exactamente cuáles son TUS villanos definitivos y cuáles puedes reconquistar.",
    module: 4,
    moduleName: "El Mapa es Tuyo",
    videoDuration: "16:10",
    phase: "mapea",
    action: "Lee el protocolo completo de reintroducción en el Módulo 4 antes de empezar. Elige el primer alimento que vas a testear. La regla base: un alimento cada 48 horas, porción pequeña, al mediodía.",
    actionNote: "Orden sugerido: avena → garbanzos → brócoli → kale → cebolla/ajo. Empieza por el que más extrañas.",
    reflection: "¿Qué alimento retirado extrañas más y esperas poder reconquistar?",
    downloads: ["El Mapa Personal de la Paradoja"],
  },
  16: {
    title: "Test de Reintroducción #1",
    subtitle: "Hoy introduces el primer alimento a testear. Las próximas 48 horas son de observación.",
    module: 4,
    moduleName: "El Mapa es Tuyo",
    videoDuration: "16:10",
    phase: "mapea",
    action: "Porción pequeña del alimento elegido en la comida del mediodía. Anota en el Tracker: hora, cantidad, sensación a las 2h, a las 6h y a las 24h. No introduces ningún otro alimento nuevo.",
    actionNote: "Las señales que buscas: hinchazón que aumenta en 2-6h, gases, cambio en las heces, fatiga post-comida. Cualquier señal débil = ese alimento no está listo aún.",
    reflection: "¿Cuál fue tu respuesta en las horas siguientes — tu cuerpo aceptó o protestó?",
    downloads: ["El Tracker Ciclo-Intestinal"],
  },
  17: {
    title: "Día de Observación",
    subtitle: "No introduces nada nuevo hoy. Solo observas y registras la respuesta del alimento del Día 16.",
    module: 4,
    moduleName: "El Mapa es Tuyo",
    videoDuration: "16:10",
    phase: "mapea",
    action: "Come según las Combinaciones Base con el alimento del Día 16 excluido. Registra en el Tracker cómo te sientes a las 10h, 14h, 18h y 22h.",
    reflection: "¿Tu cuerpo te habló claramente — hay señal o no hay señal con ese alimento?",
    downloads: [],
  },
  18: {
    title: "Test de Reintroducción #2",
    subtitle: "Si el Alimento #1 pasó el test (sin señales claras en 48h), es tuyo. Si hubo señal, anotarlo y pasar al siguiente.",
    module: 4,
    moduleName: "El Mapa es Tuyo",
    videoDuration: "16:10",
    phase: "mapea",
    action: "Documenta el resultado del Alimento #1 en el Mapa Personal (VERDE = pasó, ROJO = no pasó, AMARILLO = señal leve, reevaluar más adelante). Introduce el Alimento #2 con el mismo protocolo.",
    reflection: "¿Estás empezando a ver un patrón claro de lo que tu cuerpo acepta y lo que no?",
    downloads: ["El Mapa Personal de la Paradoja"],
  },
  19: {
    title: "Construyendo Tu Mapa Definitivo",
    subtitle: "Con cada test, tu Mapa Personal se hace más preciso. Esta es información que ningún médico ni nutricionista tiene sobre ti.",
    module: 4,
    moduleName: "El Mapa es Tuyo",
    videoDuration: "16:10",
    phase: "mapea",
    action: "Actualiza el Mapa Personal con los resultados de todos los tests hasta hoy. Escribe en verde los alimentos que pasaron, en rojo los que no, en amarillo los que necesitas más tiempo.",
    reflection: "¿Qué alimentos han sorprendido más — los que esperabas que fallaran y pasaron, o al revés?",
    downloads: ["El Mapa Personal de la Paradoja"],
  },
  20: {
    title: "Tu Protocolo Personal de Por Vida",
    subtitle: "Ya no necesitas seguir un protocolo genérico. Tienes el tuyo. Hoy lo escribes.",
    module: 4,
    moduleName: "El Mapa es Tuyo",
    videoDuration: "16:10",
    phase: "mapea",
    action: "Escribe en el Mapa Personal tus 5 reglas personales: (1) Tu orden glucémico propio. (2) Tus 3 alimentos confirmados de riesgo. (3) Tus 3 aliados seguros. (4) Tu ventana de alimentación. (5) Tus señales de alerta temprana.",
    reflection: "¿Cómo se siente saber exactamente qué le pasa a TU cuerpo — no al cuerpo genérico de un estudio?",
    downloads: ["El Mapa Personal de la Paradoja"],
  },
  21: {
    title: "El Día 22 Eres Tú",
    subtitle: "21 días. Tres sistemas reordenados. Un mapa que es tuyo para siempre.",
    module: 4,
    moduleName: "El Mapa es Tuyo",
    videoDuration: "16:10",
    phase: "mapea",
    action: "Completa la última página del Mapa Personal. Compara tu registro del Día 1 a las 4 PM con cómo te sientes hoy a la misma hora. Guarda el Mapa — es el activo más valioso que te llevas.",
    actionNote: "El Día 22 comes desde tu Mapa. No desde las reglas de nadie más. Desde el conocimiento de TU cuerpo específico.",
    reflection: "¿Qué le dirías a la mujer que eras el Día 1 de este protocolo?",
    downloads: ["El Mapa Personal de la Paradoja", "Tu Informe Personal de la Paradoja"],
  },
};
